export const SEARCH_ART = "SEARCH_ART";
export const REQUEST_ART_PENDING ="REQUEST_ART_PENDING";
export const REQUEST_ART_SUCCESS ="REQUEST_ART_SUCCESS";
export const REQUEST_ART_FAILED ="REQUEST_ART_FAILED";
export const REQUEST_UPLOAD_PAGE = "REQUEST_UPLOAD_PAGE";
export const REQUEST_LOGIN_PENDING = "REQUEST_LOGIN_PENDING";
export const REQUEST_LOGIN_SUCCESS = "REQUEST_LOGIN_SUCCESS";
export const REQUEST_LOGIN_FAILED = "REQUEST_LOGIN_FAILED";
